#!/usr/bin/perl
if($ARGV[0] =~/^-[0-9]*r$/){
$rev=1;
$i=1;
}
if($ARGV[0]=~/^-[0-9]+$/){$n=-$ARGV[0]; $i=1;}else{$n=10;$i=0;}

for($i;$i<scalar(@ARGV);$i++){
open (FILE,"< $ARGV[$i]");
print $rev ;
$k=0;
print "\n==> $ARGV[$i] <==\n";
while (<FILE>){
$k++;
}
seek(FILE,0,0);
if($k<$n){while(<FILE>){print;}
}else{
$j=0;
while (<FILE>){
if($j >= $k-$n){print;}
$j++;
}
}

close (FILE);
}
